# Server Port
server.port=8082

# Application Name
spring.application.name=API-GATEWAY

# --- ROUTES CONFIGURATION ---

# 1. Auth Service Route
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# 2. Student Service Route
spring.cloud.gateway.routes[1].id=student-service
spring.cloud.gateway.routes[1].uri=lb://STUDENT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/**

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# --- EUREKA CLIENT CONFIGURATION ---
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true